# Generated by Django 4.2.28 on 2026-02-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trainer_payment_mode',
            field=models.CharField(
                choices=[('dpp', 'DPP'), ('invoice', 'Faktura')],
                default='dpp',
                max_length=20,
                verbose_name='Typ odměny trenéra',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='trainer_rate_per_record',
            field=models.PositiveIntegerField(default=0, verbose_name='Částka za 1 záznam (Kč)'),
        ),
    ]
