# Generated by Django 4.2.28 on 2026-02-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_trainer_economics_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trainer_tax_15_enabled',
            field=models.BooleanField(default=False, verbose_name='Daň 15 %'),
        ),
    ]
