# Generated by Django 4.2.28 on 2026-02-11 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_trainer_tax_15_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Datum')),
                ('title', models.CharField(max_length=160, verbose_name='Název nákladu')),
                ('amount_czk', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Částka (Kč)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Poznámka')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vytvořeno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Náklad',
                'verbose_name_plural': 'Náklady',
                'ordering': ('-expense_date', '-id'),
            },
        ),
    ]
