# Generated by Django 4.2.28 on 2026-02-12 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_economyexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#1e5f8f', max_length=20, verbose_name='Primární barva')),
                ('secondary_color', models.CharField(default='#5f6570', max_length=20, verbose_name='Sekundární barva')),
                ('accent_color', models.CharField(default='#c62828', max_length=20, verbose_name='Akcent / varování')),
                ('consent_vop_text', models.TextField(blank=True, verbose_name='VOP')),
                ('consent_gdpr_text', models.TextField(blank=True, verbose_name='GDPR')),
                ('consent_health_text', models.TextField(blank=True, verbose_name='Prohlášení o zdravotním stavu')),
                ('payment_email_mode', models.CharField(choices=[('custom', 'IMAP/SMTP'), ('forward', 'Přesměrování na klubový email')], default='custom', max_length=20, verbose_name='Režim emailu plateb')),
                ('payment_imap_host', models.CharField(blank=True, max_length=120, verbose_name='IMAP host')),
                ('payment_imap_port', models.PositiveIntegerField(default=993, verbose_name='IMAP port')),
                ('payment_imap_user', models.CharField(blank=True, max_length=160, verbose_name='IMAP uživatel')),
                ('payment_imap_password', models.CharField(blank=True, max_length=255, verbose_name='IMAP heslo')),
                ('payment_smtp_host', models.CharField(blank=True, max_length=120, verbose_name='SMTP host')),
                ('payment_smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('payment_smtp_user', models.CharField(blank=True, max_length=160, verbose_name='SMTP uživatel')),
                ('payment_smtp_password', models.CharField(blank=True, max_length=255, verbose_name='SMTP heslo')),
                ('payment_forward_email', models.EmailField(blank=True, max_length=254, verbose_name='Přesměrovací email')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
            ],
            options={
                'verbose_name': 'Nastavení aplikace',
                'verbose_name_plural': 'Nastavení aplikace',
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Uživatel', 'verbose_name_plural': 'Uživatelé'},
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='Město'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrátor'), ('trainer', 'Trenér'), ('parent', 'Rodič')], default='parent', max_length=20, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='street',
            field=models.CharField(blank=True, max_length=120, verbose_name='Ulice'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='PSČ'),
        ),
    ]
