# Generated by Django 4.2.28 on 2026-02-12 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appsettings_alter_user_options_alter_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomyRecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Název nákladu')),
                ('amount_czk', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Částka (Kč)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Poznámka')),
                ('recurrence', models.CharField(choices=[('weekly', 'Týdně'), ('14days', '14 dní'), ('monthly', 'Měsíčně'), ('quarterly', 'Kvartálně'), ('yearly', 'Ročně')], max_length=20, verbose_name='Opakování')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Začátek')),
                ('next_run_date', models.DateField(verbose_name='Další zaúčtování')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vytvořeno')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
            options={
                'verbose_name': 'Opakovaný náklad',
                'verbose_name_plural': 'Opakované náklady',
                'ordering': ('title', 'id'),
            },
        ),
        migrations.AddField(
            model_name='economyexpense',
            name='recurring_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_expenses', to='users.economyrecurringexpense', verbose_name='Zdroj opakování'),
        ),
    ]
