# Generated by Django 4.2.28 on 2026-02-12 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_economyrecurringexpense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='economyexpense',
            name='expense_type',
            field=models.CharField(choices=[('general', 'Náklad klubu'), ('trainer_service', 'Trenérská služba (do mzdy)'), ('trainer_reimbursement', 'Proplacení nákupu (mimo mzdu)')], default='general', max_length=30, verbose_name='Typ nákladu'),
        ),
        migrations.AddField(
            model_name='economyexpense',
            name='trainer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'trainer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Trenér'),
        ),
    ]
