# Generated by Django 4.2.28 on 2026-02-14 00:05

from django.db import migrations, models


def _update_registration_confirmation_subject(apps, schema_editor):
    AppSettings = apps.get_model('users', 'AppSettings')
    old = 'Potvrzujeme přijetí registrace'
    new = 'SK MNÍŠECKO - potvrzujeme přijetí registrace'
    AppSettings.objects.filter(registration_confirmation_subject__in=['', old]).update(
        registration_confirmation_subject=new
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_appsettings_registration_confirmation_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='welcome_body',
            field=models.TextField(default='Dobrý den, vítejte v SK Mníšecko.', verbose_name='Vítejte - text'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='welcome_subject',
            field=models.CharField(default='SK MNÍŠECKO - Vítejte v SK Mníšecko', max_length=200, verbose_name='Vítejte - předmět'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='registration_confirmation_subject',
            field=models.CharField(default='SK MNÍŠECKO - potvrzujeme přijetí registrace', max_length=200, verbose_name='Potvrzení přijetí registrace - předmět'),
        ),
        migrations.RunPython(_update_registration_confirmation_subject, reverse_code=migrations.RunPython.noop),
    ]
