# Generated by Django 4.2.28 on 2026-02-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0009_appsettings_welcome_body_appsettings_welcome_subject_and_more'),
    ]

    def _backfill_default_tenant(apps, schema_editor):
        Tenant = apps.get_model('tenants', 'Tenant')
        User = apps.get_model('users', 'User')
        AppSettings = apps.get_model('users', 'AppSettings')
        EconomyExpense = apps.get_model('users', 'EconomyExpense')
        EconomyRecurringExpense = apps.get_model('users', 'EconomyRecurringExpense')

        tenant, _ = Tenant.objects.get_or_create(
            slug='default',
            defaults={'name': 'Hlavní tenant', 'active': True, 'next_child_vs': 1},
        )

        User.objects.filter(tenant__isnull=True).update(tenant=tenant)
        # username = "<tenant>:<email>"
        for row in User.objects.filter(username__isnull=True).only('id', 'email', 'tenant_id'):
            email = (row.email or '').strip().lower()
            slug = (tenant.slug if row.tenant_id == tenant.id else tenant.slug).strip().lower()
            row.username = f"{slug}:{email}"
            row.save(update_fields=['username'])

        EconomyExpense.objects.filter(tenant__isnull=True).update(tenant=tenant)
        EconomyRecurringExpense.objects.filter(tenant__isnull=True).update(tenant=tenant)

        # AppSettings: historically one global row. Keep the oldest row and attach it to default tenant.
        settings_rows = list(AppSettings.objects.order_by('id'))
        if settings_rows:
            keep = settings_rows[0]
            if keep.tenant_id is None:
                keep.tenant_id = tenant.id
                keep.save(update_fields=['tenant'])
            # Delete duplicates to satisfy OneToOne constraint.
            for extra in settings_rows[1:]:
                extra.delete()
        else:
            AppSettings.objects.create(tenant=tenant)

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='economyexpense',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='economy_expenses', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='economyrecurringexpense',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='economy_recurring_expenses', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Uživatelské jméno'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('tenant', 'email'), name='users_user_tenant_email_uniq'),
        ),
        migrations.RunPython(_backfill_default_tenant, migrations.RunPython.noop),
    ]
