# Generated by Django 4.2.28 on 2026-02-14 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=120, verbose_name='Název')),
                ('active', models.BooleanField(default=True, verbose_name='Aktivní')),
                ('next_child_vs', models.PositiveIntegerField(default=1, verbose_name='Další VS dítěte')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vytvořeno')),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenanti',
                'ordering': ('slug',),
            },
        ),
    ]
