# Generated by Django 4.2.28 on 2026-02-10 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainergroup',
            name='trainer',
            field=models.ForeignKey(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='attendance_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.attendanceoption'),
        ),
        migrations.AddField(
            model_name='membership',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.child'),
        ),
        migrations.AddField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='clubs.group'),
        ),
        migrations.AddField(
            model_name='group',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='clubs.sport'),
        ),
        migrations.AddField(
            model_name='group',
            name='trainers',
            field=models.ManyToManyField(related_name='assigned_groups', through='clubs.TrainerGroup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceoption',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_options', to='clubs.group'),
        ),
        migrations.AlterUniqueTogether(
            name='trainergroup',
            unique_together={('trainer', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('child', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('sport', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='attendanceoption',
            unique_together={('group', 'name')},
        ),
    ]
