# Generated by Django 4.2.28 on 2026-02-10 23:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendanceoption',
            options={'verbose_name': 'Docházková varianta', 'verbose_name_plural': 'Docházkové varianty'},
        ),
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Dítě', 'verbose_name_plural': 'Děti'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Skupina', 'verbose_name_plural': 'Skupiny'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Členství', 'verbose_name_plural': 'Členství'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'Sport', 'verbose_name_plural': 'Sporty'},
        ),
        migrations.AlterModelOptions(
            name='trainergroup',
            options={'verbose_name': 'Trenérská skupina', 'verbose_name_plural': 'Trenérské skupiny'},
        ),
        migrations.AddField(
            model_name='group',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Konec skupiny'),
        ),
        migrations.AddField(
            model_name='group',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Začátek skupiny'),
        ),
        migrations.AlterField(
            model_name='attendanceoption',
            name='frequency_per_week',
            field=models.PositiveSmallIntegerField(verbose_name='Frekvence / týden'),
        ),
        migrations.AlterField(
            model_name='attendanceoption',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='attendanceoption',
            name='price_czk',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena (Kč)'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=60, verbose_name='Jméno'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=60, verbose_name='Příjmení'),
        ),
        migrations.AlterField(
            model_name='child',
            name='passport_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Číslo pasu'),
        ),
        migrations.AlterField(
            model_name='child',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='group',
            name='training_days',
            field=models.JSONField(blank=True, default=list, verbose_name='Dny tréninků'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='attendance_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.attendanceoption', verbose_name='Docházková varianta'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='registered_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum registrace'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Název'),
        ),
    ]
