# Generated by Django 4.2.28 on 2026-02-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_variable_symbol_simple'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='billing_start_month',
            field=models.DateField(blank=True, null=True, verbose_name='Zařazení od měsíce'),
        ),
    ]
