# Generated by Django 4.2.28 on 2026-02-11 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_membership_billing_start_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildArchiveLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('info', 'Info'), ('registration', 'Registrace'), ('membership', 'Skupina'), ('attendance', 'Docházka'), ('profile', 'Profil')], default='info', max_length=20, verbose_name='Typ události')),
                ('message', models.TextField(verbose_name='Popis')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vytvořeno')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_archive_events', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_logs', to='clubs.child', verbose_name='Dítě')),
            ],
            options={
                'verbose_name': 'Archiv dítěte',
                'verbose_name_plural': 'Archiv dětí',
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
