# Generated by Django 4.2.28 on 2026-02-12 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_childarchivelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum přijetí')),
                ('variable_symbol', models.CharField(db_index=True, max_length=20, verbose_name='Variabilní symbol')),
                ('amount_czk', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Částka (Kč)')),
                ('sender_name', models.CharField(blank=True, max_length=160, verbose_name='Odesílatel')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Poznámka')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vytvořeno')),
            ],
            options={
                'verbose_name': 'Přijatá platba',
                'verbose_name_plural': 'Přijaté platby',
                'ordering': ('-received_date', '-id'),
            },
        ),
    ]
