# Generated by Django 4.2.28 on 2026-02-12 11:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0009_salecharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='allow_combined_registration',
            field=models.BooleanField(default=True, verbose_name='Povolit kombinaci s jinou skupinou'),
        ),
        migrations.AddField(
            model_name='group',
            name='max_members',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximální počet členů'),
        ),
        migrations.AddField(
            model_name='group',
            name='registration_state',
            field=models.CharField(choices=[('enabled', 'Zapnuto'), ('disabled', 'Vypnuto'), ('full', 'Obsazeno')], default='enabled', max_length=20, verbose_name='Stav registrace'),
        ),
        migrations.CreateModel(
            name='ClubDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Název dokumentu')),
                ('file', models.FileField(upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Soubor')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Nahráno')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_club_documents', to=settings.AUTH_USER_MODEL, verbose_name='Nahrál')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumenty',
                'ordering': ('-uploaded_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ChildFinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('proforma', 'Záloha'), ('invoice', 'Faktura'), ('payment', 'Příchozí platba'), ('sale', 'Prodejní položka'), ('refund', 'Vratka'), ('membership_end', 'Ukončení členství'), ('info', 'Info')], default='info', max_length=20, verbose_name='Typ')),
                ('direction', models.CharField(choices=[('debit', 'K úhradě'), ('credit', 'Příjem / výdej')], default='debit', max_length=10, verbose_name='Směr')),
                ('status', models.CharField(choices=[('open', 'Otevřeno'), ('closed', 'Uzavřeno'), ('cancelled', 'Storno')], default='open', max_length=12, verbose_name='Stav')),
                ('title', models.CharField(max_length=180, verbose_name='Popis')),
                ('amount_czk', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Částka (Kč)')),
                ('variable_symbol', models.CharField(blank=True, max_length=20, verbose_name='Variabilní symbol')),
                ('reference_code', models.CharField(blank=True, max_length=50, verbose_name='Referenční číslo')),
                ('note', models.TextField(blank=True, verbose_name='Poznámka')),
                ('occurred_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum události')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vytvořeno')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_entries', to='clubs.child', verbose_name='Dítě')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_finance_entries', to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_entries', to='clubs.membership', verbose_name='Členství')),
            ],
            options={
                'verbose_name': 'Finance dítěte',
                'verbose_name_plural': 'Finance dětí',
                'ordering': ('-occurred_on', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ChildConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_vop', models.BooleanField(default=False, verbose_name='VOP')),
                ('consent_gdpr', models.BooleanField(default=False, verbose_name='GDPR')),
                ('consent_health', models.BooleanField(default=False, verbose_name='Zdravotní stav')),
                ('source', models.CharField(choices=[('registration', 'Registrace'), ('completion', 'Doplnění údajů')], default='registration', max_length=20, verbose_name='Zdroj')),
                ('accepted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Potvrzeno')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='clubs.child', verbose_name='Dítě')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Souhlas dítěte',
                'verbose_name_plural': 'Souhlasy dětí',
                'ordering': ('-accepted_at', '-id'),
            },
        ),
    ]
