# Generated by Django 4.2.28 on 2026-02-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('users', '0010_appsettings_tenant_economyexpense_tenant_and_more'),
        ('clubs', '0010_group_allow_combined_registration_group_max_members_and_more'),
    ]

    def _backfill_default_tenant(apps, schema_editor):
        Tenant = apps.get_model('tenants', 'Tenant')
        Sport = apps.get_model('clubs', 'Sport')
        Group = apps.get_model('clubs', 'Group')
        Child = apps.get_model('clubs', 'Child')
        ReceivedPayment = apps.get_model('clubs', 'ReceivedPayment')
        ClubDocument = apps.get_model('clubs', 'ClubDocument')
        User = apps.get_model('users', 'User')

        tenant, _ = Tenant.objects.get_or_create(
            slug='default',
            defaults={'name': 'Hlavní tenant', 'active': True, 'next_child_vs': 1},
        )

        Sport.objects.filter(tenant__isnull=True).update(tenant=tenant)

        # Group tenant = sport.tenant
        for group in Group.objects.filter(tenant__isnull=True).select_related('sport').only('id', 'sport_id'):
            sport = Sport.objects.get(pk=group.sport_id)
            group.tenant_id = sport.tenant_id or tenant.id
            group.save(update_fields=['tenant'])

        # Child tenant = parent.tenant
        for child in Child.objects.filter(tenant__isnull=True).only('id', 'parent_id'):
            parent = User.objects.get(pk=child.parent_id)
            child.tenant_id = parent.tenant_id or tenant.id
            child.save(update_fields=['tenant'])

        ReceivedPayment.objects.filter(tenant__isnull=True).update(tenant=tenant)
        ClubDocument.objects.filter(tenant__isnull=True).update(tenant=tenant)

        # Update tenant VS counter to avoid collisions for new children.
        max_vs = 0
        for c in Child.objects.filter(tenant=tenant).only('variable_symbol'):
            vs = (c.variable_symbol or '').strip()
            if vs.isdigit():
                max_vs = max(max_vs, int(vs))
        next_vs = max_vs + 1 if max_vs else 1
        if tenant.next_child_vs != next_vs:
            tenant.next_child_vs = next_vs
            tenant.save(update_fields=['next_child_vs'])

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='child',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='clubdocument',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_documents', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='group',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='receivedpayment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_payments', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='sport',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='tenants.tenant', verbose_name='Tenant'),
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='child',
            name='passport_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Číslo pasu'),
        ),
        migrations.AlterField(
            model_name='child',
            name='variable_symbol',
            field=models.CharField(blank=True, max_length=4, verbose_name='Variabilní symbol'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Název'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('tenant', 'sport', 'name')},
        ),
        migrations.AddConstraint(
            model_name='child',
            constraint=models.UniqueConstraint(fields=('tenant', 'variable_symbol'), name='clubs_child_tenant_vs_uniq'),
        ),
        migrations.AddConstraint(
            model_name='child',
            constraint=models.UniqueConstraint(fields=('tenant', 'birth_number'), name='clubs_child_tenant_birth_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='child',
            constraint=models.UniqueConstraint(fields=('tenant', 'passport_number'), name='clubs_child_tenant_passport_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='sport',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='clubs_sport_tenant_name_uniq'),
        ),
        migrations.RunPython(_backfill_default_tenant, migrations.RunPython.noop),
    ]
