# Generated by Django 4.2.28 on 2026-02-10 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clubs.group'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='clubs.child'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.trainingsession'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingsession',
            unique_together={('group', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('session', 'child')},
        ),
    ]
