# Generated by Django 4.2.28 on 2026-02-11 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0005_variable_symbol_simple'),
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Docházka', 'verbose_name_plural': 'Docházka'},
        ),
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'verbose_name': 'Tréninkový den', 'verbose_name_plural': 'Tréninkové dny'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='clubs.child', verbose_name='Dítě'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='present',
            field=models.BooleanField(default=True, verbose_name='Přítomen'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Zaznamenáno'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.trainingsession', verbose_name='Tréninkový den'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='clubs.group', verbose_name='Skupina'),
        ),
        migrations.CreateModel(
            name='TrainerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True, verbose_name='Přítomen')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Zaznamenáno')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_attendance_records', to='attendance.trainingsession', verbose_name='Tréninkový den')),
                ('trainer', models.ForeignKey(limit_choices_to={'role': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Trenér')),
            ],
            options={
                'verbose_name': 'Docházka trenéra',
                'verbose_name_plural': 'Docházka trenérů',
                'unique_together': {('session', 'trainer')},
            },
        ),
    ]
