# Generated by Django 4.2.28 on 2026-02-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerattendance',
            name='extra_access',
            field=models.BooleanField(default=False, verbose_name='Mimo přiřazenou skupinu'),
        ),
    ]
