# Generated by Django 4.2.28 on 2026-02-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_trainerattendance_extra_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='Zrušený trénink'),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='is_extra',
            field=models.BooleanField(default=False, verbose_name='Mimo pravidelný rozvrh'),
        ),
    ]
